In [1]:
import os
import pandas as pd

def merge_csv_files_in_subfolders(main_folder, columns_to_read, cities, chunksize=10000):
    merged_data = pd.DataFrame()

    for folder_path, _, filenames in os.walk(main_folder):
        csv_files = [filename for filename in filenames if filename.endswith('.csv')]

        if len(csv_files) == 1:
            csv_file_path = os.path.join(folder_path, csv_files[0])

            # Check if the CSV file is not empty
            if os.path.getsize(csv_file_path) > 0:
                current_data = pd.read_csv(csv_file_path, usecols=columns_to_read, chunksize=chunksize)

                for chunk in current_data:
                    # Filter rows based on specified cities
                    filtered_chunk = chunk[(chunk['Origin'].isin(cities)) & (chunk['Dest'].isin(cities))]
                    merged_data = pd.concat([merged_data, filtered_chunk], ignore_index=True)

    return merged_data

main_folder = 'D:\\Assignment\\2016_original\\2016'
columns_to_read = ['FlightDate', 'Quarter', 'Year', 'Month', 'DayofMonth', 'DepTime', 'DepDel15', 'CRSDepTime', 'DepDelayMinutes', 'Origin', 'Dest', 'ArrTime', 'CRSArrTime', 'ArrDel15', 'ArrDelayMinutes']

# Specify the cities you want to include
cities_of_interest = ['ATL', 'CLT', 'DEN', 'DFW', 'EWR', 'IAH', 'JFK', 'LAS', 'LAX', 'MCO', 'MIA', 'ORD', 'PHX', 'SEA', 'SFO']

# Adjust chunksize based on available memory and CSV file size
chunk_size = 10000

merged_data = merge_csv_files_in_subfolders(main_folder, columns_to_read, cities_of_interest, chunk_size)
merged_data.to_csv('D:/Assignment/merged_final_filtered.csv', index=False)

In [3]:
def merge_csv_files_in_subfolders(main_folder, columns_to_read, cities, chunksize=10000):
    merged_data2 = pd.DataFrame()

    for folder_path, _, filenames in os.walk(main_folder):
        csv_files = [filename for filename in filenames if filename.endswith('.csv')]

        if len(csv_files) == 1:
            csv_file_path = os.path.join(folder_path, csv_files[0])

            # Check if the CSV file is not empty
            if os.path.getsize(csv_file_path) > 0:
                current_data = pd.read_csv(csv_file_path, usecols=columns_to_read, chunksize=chunksize)

                for chunk in current_data:
                    # Filter rows based on specified cities
                    filtered_chunk = chunk[(chunk['Origin'].isin(cities)) & (chunk['Dest'].isin(cities))]
                    merged_data2 = pd.concat([merged_data, filtered_chunk], ignore_index=True)

    return merged_data2

main_folder = 'D:\\Assignment\\2017_original\\2017'
columns_to_read = ['FlightDate', 'Quarter', 'Year', 'Month', 'DayofMonth', 'DepTime', 'DepDel15', 'CRSDepTime', 'DepDelayMinutes', 'Origin', 'Dest', 'ArrTime', 'CRSArrTime', 'ArrDel15', 'ArrDelayMinutes']

# Specify the cities you want to include
cities_of_interest = ['ATL', 'CLT', 'DEN', 'DFW', 'EWR', 'IAH', 'JFK', 'LAS', 'LAX', 'MCO', 'MIA', 'ORD', 'PHX', 'SEA', 'SFO']

# Adjust chunksize based on available memory and CSV file size
chunk_size = 10000

merged_data2 = merge_csv_files_in_subfolders(main_folder, columns_to_read, cities_of_interest, chunk_size)
merged_data2.to_csv('D:/Assignment/merged_final_filtered2.csv', index=False)

In [4]:
merged_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 948819 entries, 0 to 948818
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Year             948819 non-null  int64
 1   Quarter          948819 non-null  int64
 2   Month            948819 non-null  int64
 3   DayofMonth       948819 non-null  int64
 4   FlightDate       948819 non-null  object
 5   Origin           948819 non-null  object
 6   Dest             948819 non-null  object
 7   CRSDepTime       948819 non-null  int64
 8   DepTime          939523 non-null  float64
 9   DepDelayMinutes  939523 non-null  float64
 10  DepDel15         939523 non-null  float64
 11  CRSArrTime       948819 non-null  int64
 12  ArrTime          938965 non-null  float64
 13  ArrDelayMinutes  936961 non-null  float64
 14  ArrDel15         936961 non-null  float64
dtypes: float64(6), int64(6), object(3)
memory usage: 108.6+ MB

In [5]:
merged_data2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 949738 entries, 0 to 949737
Data columns (total 15 columns):
 #   Column           Non-Null Count   Dtype
---  ------           --------------   -----
 0   Year             949738 non-null  int64
 1   Quarter          949738 non-null  int64
 2   Month            949738 non-null  int64
 3   DayofMonth       949738 non-null  int64
 4   FlightDate       949738 non-null  object
 5   Origin           949738 non-null  object
 6   Dest             949738 non-null  object
 7   CRSDepTime       949738 non-null  int64
 8   DepTime          940442 non-null  float64
 9   DepDelayMinutes  940442 non-null  float64
 10  DepDel15         940442 non-null  float64
 11  CRSArrTime       949738 non-null  int64
 12  ArrTime          939883 non-null  float64
 13  ArrDelayMinutes  937878 non-null  float64
 14  ArrDel15         937878 non-null  float64
dtypes: float64(6), int64(6), object(3)
memory usage: 108.7+ MB

In [6]:
flights_df = pd.concat([merged_data, merged_data2])

In [7]:
flights_df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1898557 entries, 0 to 949737
Data columns (total 15 columns):
 #   Column           Dtype
---  ------           -----
 0   Year             int64
 1   Quarter          int64
 2   Month            int64
 3   DayofMonth       int64
 4   FlightDate       object
 5   Origin           object
 6   Dest             object
 7   CRSDepTime       int64
 8   DepTime          float64
 9   DepDelayMinutes  float64
 10  DepDel15         float64
 11  CRSArrTime       int64
 12  ArrTime          float64
 13  ArrDelayMinutes  float64
 14  ArrDel15         float64
dtypes: float64(6), int64(6), object(3)
memory usage: 231.8+ MB

In [8]:
# After merging flight data from 2016 and 2017, there are 1898557 entries out of which 948819 entries belong to 2016 and 949738 entries belong to 2017

In [13]:
flights_df.head(5)

,Year,Quarter,Month,DayofMonth,FlightDate,Origin,Dest,CRSDepTime,DepTime,DepDelayMinutes,DepDel15,CRSArrTime,ArrTime,ArrDelayMinutes,ArrDel15
0,2016,1,1,1,2016-01-01,SEA,JFK,745,741.0,0.0,0.0,1602,1610.0,8.0,0.0
1,2016,1,1,2,2016-01-02,SEA,JFK,745,737.0,0.0,0.0,1602,1613.0,11.0,0.0
2,2016,1,1,3,2016-01-03,SEA,JFK,745,743.0,0.0,0.0,1602,1547.0,0.0,0.0
3,2016,1,1,4,2016-01-04,SEA,JFK,745,737.0,0.0,0.0,1602,1551.0,0.0,0.0
4,2016,1,1,5,2016-01-05,SEA,JFK,710,708.0,0.0,0.0,1527,1524.0,0.0,0.0

In [1]:
import os
import json
import pandas as pd

def filter_and_extract_columns(folder_path, output_path, columns_to_extract, chunk_size=10000):
    result_data = pd.DataFrame()

    for root, dirs, files in os.walk(folder_path):
        for file in files:
            if file.endswith('.json') and (file.startswith('2016') or file.startswith('2017')):
                file_path = os.path.join(root, file)
                day = file[:]

                with open(file_path, 'r') as json_file:
                    data = json.load(json_file)
                    airport = data.get('data', {}).get('request', [{}])[0].get('query', None)  # Extract 'airport' from 'request'
                    date = data.get('data', {}).get('weather', [{}])[0].get('date', None)  # Extract 'date' from 'weather'

                    for hourly_data in data.get('data', {}).get('weather', []):
                        for hourly_entry in hourly_data.get('hourly', []):
                            filtered_data = {column: None for column in columns_to_extract}

                            for column in columns_to_extract:
                                if column in hourly_entry:
                                    filtered_data[column] = hourly_entry[column]
                                elif column == 'weatherDesc':
                                    weather_desc_list = hourly_entry.get(column, [])
                                    if weather_desc_list:
                                        filtered_data[column] = weather_desc_list[0].get('value', None)

                            # Use 'date' from the sibling level
                            filtered_data['date'] = date

                            filtered_data['airport'] = airport  # Assign 'airport' to the result_data

                            # Use 'day' as 'day' in the result_data
                            filtered_data['day'] = day
                            filtered_data['folder'] = os.path.basename(root)

                            result_data = pd.concat([result_data, pd.DataFrame([filtered_data])], ignore_index=True)

                            if result_data.shape[0] >= chunk_size:
                                result_data.to_csv(output_path, mode='a', header=not os.path.exists(output_path), index=False)
                                result_data = pd.DataFrame()

    if not result_data.empty:
        result_data.to_csv(output_path, mode='a', header=not os.path.exists(output_path), index=False)

# Example usage
weather_folder_path = 'D:\\Assignment\\weather-20240114T101614Z-001\\weather'
output_csv_path = 'D:/Assignment/weather.csv'
columns_to_extract = ['windspeedKmph', 'winddirDegree', 'weatherCode', 'precipMM', 'visibility', 'pressure', 'cloudcover', 'DewPointF', 'WindGustKmph', 'tempF', 'WindChillF', 'humidity', 'date', 'time', 'airport']

filter_and_extract_columns(weather_folder_path, output_csv_path, columns_to_extract, chunk_size=10000)

In [1]:
import pandas as pd

In [2]:
weather_df = pd.read_csv('D:\Assignment\weather.csv')

In [3]:
weather_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 263160 entries, 0 to 263159
Data columns (total 17 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   windspeedKmph  263160 non-null  int64
 1   winddirDegree  263160 non-null  int64
 2   weatherCode    263160 non-null  int64
 3   precipMM       263160 non-null  float64
 4   visibility     263160 non-null  int64
 5   pressure       263160 non-null  int64
 6   cloudcover     263160 non-null  int64
 7   DewPointF      263160 non-null  int64
 8   WindGustKmph   263160 non-null  int64
 9   tempF          263160 non-null  int64
 10  WindChillF     263160 non-null  int64
 11  humidity       263160 non-null  int64
 12  date           263160 non-null  object
 13  time           263160 non-null  int64
 14  airport        263160 non-null  object
 15  day            263160 non-null  object
 16  folder         263160 non-null  object
dtypes: float64(1), int64(12), object(4)
memory usage: 34.1+ MB

In [4]:
weather_df.head(2)

,windspeedKmph,winddirDegree,weatherCode,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity,date,time,airport,day,folder
0,11,318,176,0.1,10,1023,100,47,17,49,46,91,2016-01-01,0,"ATL, Hartsfield-Jackson Atlanta International ...",2016-1.json,ATL
1,13,317,176,0.0,10,1023,100,44,22,46,42,92,2016-01-01,100,"ATL, Hartsfield-Jackson Atlanta International ...",2016-1.json,ATL

In [5]:
weather = weather_df.drop('day', axis = 1).head(3)

In [37]:
weather.head()

,windspeedKmph,winddirDegree,weatherCode,precipMM,visibility,pressure,cloudcover,DewPointF,WindGustKmph,tempF,WindChillF,humidity,date,time,airport,folder
0,11,318,176,0.1,10,1023,100,47,17,49,46,91,2016-01-01,0.0,"ATL, Hartsfield-Jackson Atlanta International ...",ATL
1,13,317,176,0.0,10,1023,100,44,22,46,42,92,2016-01-01,100.0,"ATL, Hartsfield-Jackson Atlanta International ...",ATL
2,14,315,122,0.0,10,1023,100,41,26,43,38,92,2016-01-01,200.0,"ATL, Hartsfield-Jackson Atlanta International ...",ATL

In [7]:
import pandas as pd
csv1 = pd.read_csv('D:\Assignment\merged_final_filtered.csv')
csv2 = pd.read_csv('D:\Assignment\merged_final_filtered2.csv')
flights = pd.concat([csv1, csv2])

In [8]:
flights.info()

<class 'pandas.core.frame.DataFrame'>
Index: 1898557 entries, 0 to 949737
Data columns (total 15 columns):
 #   Column           Dtype
---  ------           -----
 0   Year             int64
 1   Quarter          int64
 2   Month            int64
 3   DayofMonth       int64
 4   FlightDate       object
 5   Origin           object
 6   Dest             object
 7   CRSDepTime       int64
 8   DepTime          float64
 9   DepDelayMinutes  float64
 10  DepDel15         float64
 11  CRSArrTime       int64
 12  ArrTime          float64
 13  ArrDelayMinutes  float64
 14  ArrDel15         float64
dtypes: float64(6), int64(6), object(3)
memory usage: 231.8+ MB

In [29]:
# flights.to_csv('flights.csv', index = False)

In [10]:
flights.head()

,Year,Quarter,Month,DayofMonth,FlightDate,Origin,Dest,CRSDepTime,DepTime,DepDelayMinutes,DepDel15,CRSArrTime,ArrTime,ArrDelayMinutes,ArrDel15
0,2016,1,1,1,2016-01-01,SEA,JFK,745,741.0,0.0,0.0,1602,1610.0,8.0,0.0
1,2016,1,1,2,2016-01-02,SEA,JFK,745,737.0,0.0,0.0,1602,1613.0,11.0,0.0
2,2016,1,1,3,2016-01-03,SEA,JFK,745,743.0,0.0,0.0,1602,1547.0,0.0,0.0
3,2016,1,1,4,2016-01-04,SEA,JFK,745,737.0,0.0,0.0,1602,1551.0,0.0,0.0
4,2016,1,1,5,2016-01-05,SEA,JFK,710,708.0,0.0,0.0,1527,1524.0,0.0,0.0

In [11]:
weather.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3 entries, 0 to 2
Data columns (total 16 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   windspeedKmph  3 non-null      int64
 1   winddirDegree  3 non-null      int64
 2   weatherCode    3 non-null      int64
 3   precipMM       3 non-null      float64
 4   visibility     3 non-null      int64
 5   pressure       3 non-null      int64
 6   cloudcover     3 non-null      int64
 7   DewPointF      3 non-null      int64
 8   WindGustKmph   3 non-null      int64
 9   tempF          3 non-null      int64
 10  WindChillF     3 non-null      int64
 11  humidity       3 non-null      int64
 12  date           3 non-null      object
 13  time           3 non-null      int64
 14  airport        3 non-null      object
 15  folder         3 non-null      object
dtypes: float64(1), int64(12), object(3)
memory usage: 512.0+ bytes

In [12]:
weather['time'] = weather['time'].astype(float)

In [40]:
weather.rename(columns = {'folder':'city'}, inplace = True)

In [41]:

merged_data = flights.merge(weather, left_on=['FlightDate','ArrTime','Origin'], right_on=['date', 'time','city'], how = 'left')

MemoryError: Unable to allocate 43.5 MiB for an array with shape (3, 1898557) and data type float64

In [42]:
# Getting memory error